---
abstract: 'URIs that magically set a default base'
author:
  - 'Joe McMahon (mcmahon@ibiblio.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-ImpliedBase
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  Test::Simple: 0.44
  URI: 0
version: 0.08
